=head1 bin/harvest scripts




=head1 crossref.pl

Fetches records from the CrossRef site.

=head1 feeds.pl

Fetches records from the registered RSS feeds.

=head1 lib-harvest.pl



=head1 oai.pl

Fetches records from the OAI archives registered.

=head1 opendoar-fetch.pl



=head1 plugin-manager.pl



=head1 scrape.pl



=head1 web-harvester.pl



=head1 z3950.pl

