=head1 Top level 'bin' scripts and miscellaneous.



=head2 cleanup.pl

Calls cleanAll on entries.

=head2 cmd.pl

xPapers shell.

=head2 eval.pl

Imports config and then evals ARGV[0].

=head2 plugin-manager.pl

Tests harvester plugins.

=head2 printdiff.pl

Pretty prints xPapers::Diff objects.

=head2 sshblock.sh



=head2 start

Restarts the Apache and Sphinx servers.

=head2 wrapper.pl

Executes scripts, logs resutls and notifies administrators in case of errors.

=head2 operations/batchimport.pl

Imports entries from files.

=head2 operations/update_cats.pl

Applies changes to categories batched in the cat_edits table.

